# Generated by Django 4.2.4 on 2023-08-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_genre_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
    ]
