# Generated by Django 4.2.4 on 2023-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_bookborrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
