# Generated by Django 4.2.4 on 2023-11-01 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0007_bookborrow_fine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookborrow',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='return_date',
        ),
        migrations.CreateModel(
            name='BookBorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(null=True)),
                ('fine', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
